### ISSUE TITLE
'StaticHashTableV1' object has no attribute 'init'

### ISSUE THREAD

**Issue by JnaneshPrabhu** [JHart96/keras_elmo_embedding_layer#3]
Hi,
I am new into NLP and TF and wanted to use state of art embeddings into a simple news category classification problem. When I use your elmo.py code and try to build a LSTM model using it, it shows the following error:
**'StaticHashTableV1' object has no attribute 'init'**
This error is shown in this line:
self.lookup_table.init.run(session=K.get_session())

I checked it is related to initializing the table using  tf.tables_initializer(). But I am getting the same error or maybe I am using it in wrong way
Kindly help
Thanks

**Comment by JHart96** [comment]
Hi,

Have you tried running one of the examples from the repo? Do they work for you? If not, it might be an issue with the Tensorflow or Keras versions you're running.

If they do work, it might be an issue in your implementation, if that's the case, could you provide a minimal working example so that I can recreate the bug?

Which versions of Tensorflow and Keras are you using?

Kind regards,
Jordan

**Comment by JnaneshPrabhu** [comment]
Hi,
It was indeed the version of Tensorflow and keras. Sorry to bother you on the same. And great work! Really helps to have a Elmo as a layer in keras.
Cheers!
